module Callback
{
  interface Afficheur ;
  
  interface Calculant
  {
    oneway void faitLeCalcul (in double val, in Afficheur peer) ;
  } ;

  interface Afficheur
  {
    oneway void afficheRes(in string res) ;
    oneway void arreteORB() ;
  } ;

} ;

